name: backup_hasura
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.0
  dio: ^4.0.4
  hive: ^2.0.5
  bitsdojo_window: ^0.1.1+1 
  file_picker: ^4.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.0.0


  flutter_lints: ^1.0.0





flutter:
  assets:
  - assets/logo.png  
 
  uses-material-design: true

msix_config:
  display_name: Hasura Backup
  publisher_display_name: Hasura Backup
  identity_name: com.senuntech
  msix_version: 1.0.0.0
  logo_path: assets/logo.png

